spring:
  datasource:
    initialization-mode: always
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

file:
  location: /Users/cs/board

logging:
  level:
    root: info
    org:
      hibernate:
        type:
          descriptor:
            sql: OFF



## port & login session id 만료시간 설정
server:
  port:
    8080
  servlet:
    session:
      timeout:
        1800s

schedule:
  year: "*"
  month: "*"
  day: "*"
  dayOfWeek: "?"
  hour: "*"
  minute: "13"
  second: "1"
## email 인증 관련 설정
smtp:
  platform: naver
  sender:
    id: katd6@naver.com
    password: KIM13032695!
  template:
    title: planet 인증 메일입니다.
    content: 안녕하세요, planet 회원가입을 위한 인증번호를 안내드립니다, 하기의 가입정보를 입력하신 것이 맞다면 아래의 인증번호를 입력해주세요.



---
config:
  activate:
    on-profile: dev
spring:
  datasource:
    driver-class-name : com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/planet
    username: root
    password: 1234
---
config:
  activate:
    on-profile: production
spring:
  datasource:
    driver-class-name : com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/planet
    username: root
    password: 1234
---